<table>
        <td>
        <td><img src="https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/logo_ECI.png" width="400"/></td>
        <td>&nbsp;</td>
        <td>
            <h1 style="font-size:200%;color:blue;text-align:center">    <FONT COLOR="blue"> DataFrames </p> Parte 3: .iloc y loc  </FONT>         </h1></td>         
        <td>
            <tp><p style="font-size:99%;text-align:center">Diplomado Ciencia de Datos </p></tp>
            <tp><p style="font-size:115%;text-align:center">2026-1</p></tp>
            <tp><p style="font-size:115%;text-align:center">Prof. Fabián Sánchez</p></tp>
        </td>
    </tr>
</table>


# <FONT SIZE=5 COLOR="red"> Contenidos del Notebook </FONT>

En este notebook encontrará:

- Selección de filas y columnas

  + *.iloc*
  + *.loc*

- La función *Replace*


Iniciaremos importando la librería *pandas*

In [117]:
# importamos las librerías
import pandas as pd
import numpy as np

In [ ]:
# cargamos los datos: apartamentos
aptos = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/master/apartamentos.csv")
aptos.head()

,Unnamed: 0,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,1,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,2,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,3,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,4,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,5,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si


In [ ]:
# cargamos los datos: hepatitis
hepatitis = pd.read_excel("https://raw.github.com/Fabian830348/Bases_Datos/master/hepatitis.xlsx")
hepatitis.head()

,Clase,Edad,Sexo,Esteroides,Antivirales,Fatiga,Malestar,Anorexia,Higado Grande,Cirrosis,Bazo palpable,Arañas,Ascites,Varices,Billirubina,Fosfato,SGOT,Albumina,Protina,Histologia
0,Vivo,30,Mujer,No,Sí,Sí,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,1.0,85,18,4.0,0,No
1,Vivo,50,Hombre,No,Sí,No,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,0.9,135,42,3.5,0,No
2,Vivo,78,Hombre,Sí,Sí,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,96,32,4.0,0,No
3,Vivo,31,Hombre,,No,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,0.7,46,52,4.0,80,No
4,Vivo,34,Hombre,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,Sí,1.0,0,200,4.0,0,No


Vamos a trabajar inicialmente con apartamentos

In [ ]:
# eliminamos la primera variable
aptos.drop(columns = ["Unnamed: 0"], inplace = True)

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si


# <FONT SIZE=5 COLOR="green"> 1. Acceder a los elementos del DataFrame </FONT>

Para acceder a los elementos, o a las filas o columnas del DataFrame podemos usar:

- ***iloc*** : para acceder por la posición
- ***loc.*** : para acceder por el nombre

Si usamos la primera instrucción

- ***df.iloc[i,j]*** : elemento de la fila i y columna j.

- ***df.iloc[i]*** : devuelve la fila i

- ***df.iloc[lista i , lista j]*** : devuelve un data.frame con las filas en lista i y columnas en columna j.

- ***df.iloc[:, j]*** : devuelve toda columna j.

Si usamos la instrucción **.loc**

- ***df.loc[nombre fila , nombre columna]***: es lo mismo anterior pero con los nombres.

- ***df[nombre columna]*** : devuelve las columnas en name columnas

- ***df.columna*** : otra forma para acceder a una columna que en el nombre no tenga espacios en blanco.


<br>
<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/DATAFRAME.png?raw=true" alt="centered image" width="600" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

## <FONT SIZE=4 COLOR="magenta"> 1.1 Ejemplos con **.iloc** </FONT>


<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/iloc1.png?raw=true" alt="centered image" width="600" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

In [ ]:
aptos.head(6)

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
5,140.0,71.00,norte,3,3,2,no,si,0.120,31.145508,si


**Para seleccionar un elemento**

Elemento de la fila $i$ y columna $j$

$$datos.iloc[i,j]$$

In [ ]:
# para seleccionar un elemento de la fila i, columna j.
aptos.iloc[3,4]

np.int64(3)

In [ ]:
aptos.iloc[0, 9]

np.float64(14.923002)

**Para seleccionar una fila**

Para seleccionar la fila $i$

$$datos.iloc[i]$$

In [ ]:
# para seleccionar una fila, simplemente no especificamos la columna
aptos.iloc[3]

,3
precio,123.0
mt2,61.85
ubicacion,norte
estrato,2
alcobas,3
banos,2
balcon,si
parqueadero,si
administracion,0.13
avaluo,27.0


In [ ]:
# si quiero varias filas
aptos.iloc[[0,3,4]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.05,14.923002,no
3,123.0,61.85,norte,2,3,2,si,si,0.13,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.00,39.567000,si


In [ ]:
# si quiero un rango de filas. La instrucción range(a,b): inicia en a y termina en b-1
aptos.iloc[range(2,8)]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
5,140.0,71.00,norte,3,3,2,no,si,0.120,31.145508,si
6,145.0,54.83,norte,3,2,2,si,si,0.140,27.000000,si
7,160.0,69.00,norte,3,3,2,si,si,0.127,29.672435,si


**Para seleccionar una columna**

Para seleccionar la columna $j$

$$datos.iloc[:,j]$$

In [ ]:
aptos.iloc[:,2]

,ubicacion
0,norte
1,norte
2,norte
3,norte
4,norte
...,...
689,laureles
690,laureles
691,laureles
692,laureles


In [ ]:
# seleccionar varias columnas
aptos.iloc[:,[2,5,8]]

,ubicacion,banos,administracion
0,norte,1,0.050
1,norte,1,0.069
2,norte,2,0.000
3,norte,2,0.130
4,norte,2,0.000
...,...,...,...
689,laureles,3,0.570
690,laureles,3,0.450
691,laureles,4,0.747
692,laureles,3,0.340


**Varias columnas y varias filas**

<center><img src="https://github.com/Fabian830348/cursos/blob/master/intro/iloc2.png?raw=true" alt="centered image" width="450" height="350"></center> <center><figcaption> <FONT SIZE=1 COLOR="black"> Fuente: Elaboración propia  </FONT> <figcaption></center>

In [ ]:
# filas 1 y 3 y columnas 0 y 1
aptos.iloc[[1,3], [0,1]]

,precio,mt2
1,93.0,56.92
3,123.0,61.85


In [ ]:
# las primeras 100 filas
aptos.iloc[0:100]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...,...,...,...
95,220.0,94.00,poblado,6,3,2,no,si,0.250,107.858000,si
96,220.0,77.00,poblado,5,3,2,no,si,0.235,124.200000,si
97,225.0,78.40,poblado,6,1,2,si,si,0.250,137.438000,si
98,228.0,85.00,poblado,6,3,2,no,si,0.308,136.561000,no


In [ ]:
# para seleccionar la segunda, tercera y primera fila
aptos.iloc[[1,2,0]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no


In [ ]:
# la novena columna
aptos.iloc[: , 9 ]

,avaluo
0,14.923002
1,27.000000
2,15.738427
3,27.000000
4,39.567000
...,...
689,233.784000
690,258.850000
691,326.157000
692,324.114000


In [ ]:
# para seleccionar de la columna 3 en adelante
aptos.iloc[: , 3:]

,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,3,3,1,si,si,0.050,14.923002,no
1,2,2,1,si,si,0.069,27.000000,si
2,3,2,2,no,no,0.000,15.738427,no
3,2,3,2,si,si,0.130,27.000000,no
4,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...
689,5,4,3,si,si,0.570,233.784000,si
690,6,4,3,si,si,0.450,258.850000,si
691,6,3,4,no,si,0.747,326.157000,si
692,5,3,3,si,si,0.340,324.114000,si


## <FONT SIZE=4 COLOR="magenta"> 1.2 Ejemplos con **.loc** </FONT>

Veamos algunos ejemplos con **.loc**.

Recordemos que en *.iloc* se busca por posición y en *.loc* por nombre.

In [ ]:
aptos.columns

Index(['precio', 'mt2', 'ubicacion', 'estrato', 'alcobas', 'banos', 'balcon',
       'parqueadero', 'administracion', 'avaluo', 'terminado'],
      dtype='object')

In [ ]:
# verificar el nombre de los índices
aptos.index

RangeIndex(start=0, stop=694, step=1)

In [ ]:
aptos.loc[ 5 , "avaluo"]

np.float64(31.145508)

In [ ]:
# la columna ubicacion
aptos.loc[:,"ubicacion"]

,ubicacion
0,norte
1,norte
2,norte
3,norte
4,norte
...,...
689,laureles
690,laureles
691,laureles
692,laureles


In [ ]:
# seleccionar la fila 5
aptos.loc[5]

,5
precio,140.0
mt2,71.0
ubicacion,norte
estrato,3
alcobas,3
banos,2
balcon,no
parqueadero,si
administracion,0.12
avaluo,31.145508


In [ ]:
aptos.loc[: , "estrato": ]

,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,3,3,1,si,si,0.050,14.923002,no
1,2,2,1,si,si,0.069,27.000000,si
2,3,2,2,no,no,0.000,15.738427,no
3,2,3,2,si,si,0.130,27.000000,no
4,4,3,2,si,no,0.000,39.567000,si
...,...,...,...,...,...,...,...,...
689,5,4,3,si,si,0.570,233.784000,si
690,6,4,3,si,si,0.450,258.850000,si
691,6,3,4,no,si,0.747,326.157000,si
692,5,3,3,si,si,0.340,324.114000,si


In [ ]:
# seleccionar las columnas precio, mt2 y avaluo y las filas 2,5,6,7
aptos.loc[[2,5,6,7] , ["precio", "mt2", "avaluo"]]

,precio,mt2,avaluo
2,100.0,66.40,15.738427
5,140.0,71.00,31.145508
6,145.0,54.83,27.000000
7,160.0,69.00,29.672435


In [ ]:
# otro ejemplo
aptos.loc[ [10,20,0,7] , ["ubicacion","parqueadero"]]

,ubicacion,parqueadero
10,occidente,no
20,occidente,si
0,norte,si
7,norte,si


# <FONT SIZE=5 COLOR="green"> 2. La función Replace </FONT>

Podemos cambiar elementos de las columnas con la función replace

$$datos[``Variable"] = datos[``Variable"].replace(\{Valor\_actual : Valor\_nuevo\})$$

Veamos un ejemplo

In [ ]:
aptos.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,79.0,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,93.0,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,100.0,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si


In [ ]:
# cambiar el 79 93 100 por hola, muuu y chau en la primera columna
aptos2 = aptos.copy()
aptos2["precio"] = aptos2["precio"].replace({79 : "hola" , 93: "muuu" , 100 : "chau"})

In [ ]:
aptos2.head()

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
0,hola,43.16,norte,3,3,1,si,si,0.050,14.923002,no
1,muuu,56.92,norte,2,2,1,si,si,0.069,27.000000,si
2,chau,66.40,norte,3,2,2,no,no,0.000,15.738427,no
3,123.0,61.85,norte,2,3,2,si,si,0.130,27.000000,no
4,135.0,89.80,norte,4,3,2,si,no,0.000,39.567000,si


# <FONT SIZE=5 COLOR="green"> 3. Revisar donde hay cierto elemento </FONT>

Supongamos que queremos saber las posiciones donde el precio es de 120 millones.

Para saber una determinada posición usamos la instrucción

$$np.where(condicion)$$

In [ ]:
# cuántos apartamentos tienen precio de 120 millones
sum(aptos["precio"] == 120)

8

In [ ]:
# saber las posiciones donde el precio es de 120 millones
np.where(aptos["precio"] == 120)


(array([ 27, 362, 363, 364, 365, 366, 528, 529]),)

Podemos ver la información de estos apartamentos

In [ ]:
aptos.iloc[[27, 362, 363, 364, 365, 366, 528, 529]]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no


In [ ]:
aptos[aptos.precio == 120]

,precio,mt2,ubicacion,estrato,alcobas,banos,balcon,parqueadero,administracion,avaluo,terminado
27,120.0,57.0,occidente,3,2,2,no,no,0.000,68.302000,si
362,120.0,60.0,aburra sur,3,3,2,si,no,0.000,121.000000,si
363,120.0,58.0,aburra sur,3,3,2,no,si,0.125,52.633209,si
364,120.0,60.0,aburra sur,3,2,2,si,no,0.000,44.469049,si
365,120.0,80.0,aburra sur,3,2,1,si,no,0.000,31.083971,si
366,120.0,60.0,aburra sur,3,3,1,no,no,0.092,28.684288,si
528,120.0,58.0,belen guayabal,3,3,2,no,si,0.067,90.000000,si
529,120.0,117.0,belen guayabal,3,4,1,si,no,0.000,61.099000,no


# <FONT SIZE=5 COLOR="green"> 4. Ejemplo importante </FONT>

In [123]:
# cargamos los datos crédito
credito = pd.read_csv("https://raw.githubusercontent.com/Fabian830348/Bases_Datos/refs/heads/master/credit_dip.csv")
credito.head()

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
0,yes,0,37.66667,4.5200,0.033270,124.983300,yes,no,3,54,1,12
1,yes,0,33.25,2.4200,0.005217,9.854167,no,no,3,34,1,13
2,yes,0,33.66667,4.5000,0.004156,15.000000,yes,no,4,5o,1,5
3,yes,0,30.5,2.5400,0.065214,137.869200,no,no,0,25,1,7
4,yes,0,32.16667,9.7867,0.067051,546.503300,yes,no,2,64,1,5


In [125]:
# información de los datos
credito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   card         1319 non-null   object 
 1   reports      1319 non-null   int64  
 2   age          1319 non-null   object 
 3   income       1319 non-null   float64
 4   share        1319 non-null   float64
 5   expenditure  1319 non-null   float64
 6   owner        1319 non-null   object 
 7   selfemp      1319 non-null   object 
 8   dependents   1319 non-null   int64  
 9   months       1319 non-null   object 
 10  majorcards   1319 non-null   int64  
 11  active       1319 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 123.8+ KB


In [126]:
# revisar cadenas de texto en age
credito["age"].unique()

array(['37.66667', '33.25', '33.66667', '30.5', '32.16667', '23.25',
       '27.91667', '29.16667', '37.0', '28.41667', ' ', '30.0',
       '28.83333', '35.33333', '40.08333', '29.5', '39.5', '45.75',
       '35.25', '25.16667', '34.25', '35.75', '42.66667', '30.25',
       '21.66667', '22.25', '40.0', '21.83333', '29.41667', '24.91667',
       '21.0', '23.83333', '42.83333', '42.58333', '36.58333', '26.75',
       '27.75', '26.25', '23.33333', '29.91667', '38.33333', '28.16667',
       '35.58333', '37.75', '26.08333', '49.75', '24.25', '20.66667',
       '23.75', '25.75', '32.91667', '34.33333', '44.66667', '21.16667',
       '25.08333', '27.16667', '26.41667', '22.0', '27.33333', '26.16667',
       '40.75', '42.08333', '24.66667', '30.75', '27.41667', '33.0',
       '37.33333', '26.58333', '24.33333', '25.25', '0.5', '32.83333',
       '32.75', '54.583330000000004', '19.58333', '29.33333', '40.16667',
       '41.25', '34.5', '23.66667', '53.666669999999996', '34.0',
       '44.91667'

In [127]:
pd.to_numeric(credito.age, errors='coerce').isna()

,age
0,False
1,False
2,False
3,False
4,False
...,...
1314,False
1315,False
1316,False
1317,False


In [128]:
np.where(pd.to_numeric(credito.age, errors='coerce').isna())

(array([11, 15]),)

In [129]:
credito.age[[11,15]]

,age
11,
15,


In [ ]:
# vamos a hacer coherción de datos: forzar a que se convierta en uno u otro tipo
credito.age= pd.to_numeric(credito.age, errors='coerce')

**veamos otra variable**

In [130]:
credito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   card         1319 non-null   object 
 1   reports      1319 non-null   int64  
 2   age          1319 non-null   object 
 3   income       1319 non-null   float64
 4   share        1319 non-null   float64
 5   expenditure  1319 non-null   float64
 6   owner        1319 non-null   object 
 7   selfemp      1319 non-null   object 
 8   dependents   1319 non-null   int64  
 9   months       1319 non-null   object 
 10  majorcards   1319 non-null   int64  
 11  active       1319 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 123.8+ KB


In [131]:
# revisar cadenas de texto en months
credito["months"].unique()

array(['54', '34', '5o', '25', '64', '7', '77', '97', '65', '24', '36',
       '42', '26', '12o', '168', '96', '60', '28', '115', '12', '18',
       '13', '38', '74', '9', '14', '4o', '108', '46', '2', '8', '156',
       '98', '30', '0', '6', '48', '216', '33', '20', '3', '16', '182',
       '78', '4', '53', '144', '5', '94', '37', '15', '177', '172', '288',
       '87', '69', '161', '72', '1', '51', '120', '126', '27', '32', '52',
       '114', '180', '41', '67', '62', '84', '264', '164', '55', '57',
       '50', '11', '10', '17', '61', '128', '56', '45', '19', '252', '23',
       '35', '43', '300', '31', '76', '121', '21', '230', '204', '179',
       '40', '80', '59', '93', '49', '22', '408', '44', '63', '372',
       '113', '106', '90', '540', '188', '146', '301', '192', '150', '85',
       '133', '131', '270', '102', '151', '70', '125', '159', '101', '75',
       '117', '132', '158', '200', '210', '250', '109', '240', '268',
       '162', '135', '66', '110', '134', '160', '122', '8

In [135]:
pd.to_numeric(credito.months, errors='coerce').isna()

,months
0,False
1,False
2,True
3,False
4,False
...,...
1314,False
1315,False
1316,False
1317,False


In [136]:
sum(pd.to_numeric(credito.months, errors='coerce').isna())

3

In [147]:
np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0]

array([ 2, 14, 32])

In [149]:
credito.iloc[list(np.where(pd.to_numeric(credito.months, errors='coerce').isna())[0])]

,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
2,yes,0,33.66667,4.500,0.004156,15.000,yes,no,4,5o,1,5
14,yes,0,35.33333,1.908,0.026907,42.615,yes,no,2,12o,0,5
32,no,1,24.91667,3.150,0.000381,0.000,yes,no,1,4o,1,5


**Para pensar un poco**

In [158]:
# función para detectar
def problema_texto(datos, x):
  u = np.where(pd.to_numeric(credito.months, errors='coerce').isna())
  print(u)
  v = credito.iloc[list(np.where(pd.to_numeric(datos[x], errors='coerce').isna())[0])]
  return v

In [160]:
problema_texto(credito, "age")

(array([ 2, 14, 32]),)


,card,reports,age,income,share,expenditure,owner,selfemp,dependents,months,majorcards,active
11,no,0,,1.98,0.000606,0.000,yes,no,2,36,1,0
15,yes,0,,3.20,0.125819,335.435,yes,no,1,168,1,22
